apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-rhro
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-rhro
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-rhro
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-rhro
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-rhro
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jxby-tenant/rhtap-demo-app/hacbs-test-project-rhro@sha256:08146c84cf53ea0505faadcf0972b66d0be1f3d4b3c340068e6cce68d4477e45
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
