apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-rhro
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jxby-tenant/rhtap-demo-app/hacbs-test-project-rhro@sha256:08146c84cf53ea0505faadcf0972b66d0be1f3d4b3c340068e6cce68d4477e45
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
